

CREATE TABLE "COUNTRY_TABLE" (
    "ID" INT AUTO_INCREMENT PRIMARY KEY,
    "COUNTRY_NAME" VARCHAR(255),
    "COUNTRY_CAPITAL" VARCHAR(255)
);

INSERT INTO "COUNTRY_TABLE" ("COUNTRY_NAME", "COUNTRY_CAPITAL") VALUES ('India', 'New Delhi');
INSERT INTO "COUNTRY_TABLE" ("COUNTRY_NAME", "COUNTRY_CAPITAL") VALUES ('United States', 'Washington DC');